### ISSUE TITLE
Design Documents

### ISSUE THREAD

**Issue by genxhero** [genxhero/fliquor#1]
Here are my tentative frontend routes, backend routes,  sample state, and database schema

**Comment by s-pangburn** [comment]
Excellent work Aaron! Here's my feedback for your proposal:

## MVP List
- [ ] The content of this page is perfect! However, the formatting needs a little work. Be sure to copy the formatting you see in the Bluebird wiki [here](https://github.com/appacademy/bluebird/wiki/mvp-list) exactly.

## Schema
- [ ] This also looks good! The formatting is great too. I would recommend changing your `has_many` and `belongs_to` associations to use `backticks` with the proper formatting. Would just make it slightly easier to read 🙂 
- [ ] Include `indexed`, `primary key`, and `foreign key` in your Details column for each table, ideally.

## Sample State
- [ ] Don't include your `sessionTokens` in your sample state! That's sensitive information for the user and should not be exposed on the frontend!
- Otherwise, looks good!

## Backend Routes
- [ ] Definitely wrap your routes in `backticks`! (This includes the HTTP verb)
- [ ] Keep in mind these backend routes will only serve up JSON data, not HTML pages. Update your descriptions to reflect this!
- [ ] Your wildcard variables aren't formatted correctly under "Tags" (ex. you have `photos/photoId/tags` instead of `photos/:photo_id/tags`) Keep in mind that Rails still wants variables sent up in `snake_case` and will create your routes accordingly.

## Frontend Routes
- [ ] This doesn't look complete. Half your routes are the same (`/photos`), and they should all be written with `backticks`. Make sure you have clear routes for all features of your website (uploading photos, creating albums, etc.)

## Frontend Components
- [ ] This page isn't needed.

Let me know once you're finished addressing this feedback and I can take another look!

**Comment by genxhero** [comment]
Most of the pages on flickr are under the url of /photos, I checked

What do you mean by backticked?

**Comment by genxhero** [comment]
It seems that most of the routes i made didn't get saved the last time i saved

**Comment by s-pangburn** [comment]
I see. That would probably be difficult to implement in practice, so I still recommend being more specific with the routes, if possible.

By backticks I mean the key left to the number 1 on the keyboard " \` ", which, when you wrap text with it in Markdown, it `looks like this`.

**Comment by genxhero** [comment]
I agree that their routes are kind of a cluster...am I allowed to take
liberties with the routes and just have actual tag index page, albums
index page etc?

Have you navigated through flickr lately lol

**Comment by genxhero** [comment]
I've been tinkering with the frontend routes hows it looking?
Would it be better to do:

/albums/
/tags/
/photos/

?

**Comment by genxhero** [comment]
Also I do not know how to project time

**Comment by genxhero** [comment]
It would definetely be easier if i could do my frontend routes
resembling the backend route structure more

**Comment by genxhero** [comment]
I wont know when i am finished until you give me the stamp of
approval, hows it looking now?

**Comment by s-pangburn** [comment]
This is good! Stamp of approval granted 💯 Feel free to start after the assessment is over tomorrow!
