### ISSUE TITLE
User Signup/Login/Errors

### ISSUE THREAD

**Issue by genxhero** [genxhero/fliquor#2]
Functionality and the majority of styling is live, please review :)

**Comment by s-pangburn** [comment]
Looking good Aaron! Here's my feedback:

- [ ] The text on your splash page isn't quite aligned in the center of my screen. I'm sure it's probably aligned on yours, but you should use more robust CSS to ensure it works on a variety of desktop displays (mobile won't be required for this project, as it would double your work).
   - I recommend using a flexbox for the text and simply align-items in the center of the screen.
Screenshot of what I mean:
![screen shot 2018-10-11 at 9 43 07 am](https://user-images.githubusercontent.com/8031316/46820161-5d2fa180-cd3a-11e8-8d71-37565392de02.png)

- [ ] In your search bar, the text should have more padding on the left and right. Maybe 10 more pixels?
- [ ] If I click the "fliquor" logo without logging in, it takes me to `/home`. It's fine if this is intended behavior, but I would just think it would link to the splash.
- [ ] After being taken to `/home`, if I press the "Back" button, I get the "React is not working" page :/ No error in the chrome console, which is a bit baffling?
- [ ] Your signup button text should highlight on hover the way it does on the Flickr website (you don't need the fade or anything though). This small thing will make your website feel more "interactive" and "professional"
    - [ ] Same with Signup in the nav bar
- [ ] There needs to be just a little more space between the Login and Signup buttons in the nav. It looks a little cramped as-is.
  - [ ] Actually, the Fliquor logo should probably have just a few more pixels of margin/padding on the left as well.
- [ ] Hmmm... I think the styling of your `sessionForm` component could use some work. The transparent effect is super cool, so you can keep that and the theming, but in terms of spacing, it would look more trendy and professional if you just straight-up copied the style of the Yahoo! sign up form (no need for all the extra fields and links and legal stuff, just the underlined input fields with clean placeholder text):
![screen shot 2018-10-11 at 9 57 37 am](https://user-images.githubusercontent.com/8031316/46820884-1b9ff600-cd3c-11e8-8ea2-cb482011c164.png)
- [ ] Also your `sessionForm` component is another one that seems to have trouble staying in the center of the screen. Again, I would recommend flexbox.
- [ ] Nice highlight effect for the Login and Signup buttons on `sessionForm`, but they should also set `cursor: pointer` on hover (this is standard practice in the industry and without it your site will feel unpolished to a recruiter)
- [ ] After logging in, "You" in the nav doesn't `cursor: pointer` on hover. Neither does Log Out, which should probably also darken a little like the cloud does so the site stays consistent.
- [ ] There needs to be more spacing between the upload cloud logo and Logout.
- [ ] The search bar here also needs to have more padding on the left and right.
- [ ] Logout doesn't work. I get `DELETE - 500 (Internal Server Error)`
- [ ] I can't test anymore because I can't log out lol
- [ ] You need a demo login if you don't have one already.

**Comment by genxhero** [comment]
I'll spend more time on the styling punch list items as time allows; we already took care of the You link, the logging out, the centering. and i believe I already got most of the highlight effects.

Linking to /home while logged out is intentional, as Flickr allows one to reach the index logged out as well.

**Comment by s-pangburn** [comment]
Hi Aaron, I really would prefer the items on this checklist be done before I can review your next feature. It's App Academy policy that each feature be complete before moving on. You're free to work on features beyond this one, but I can't review any others you get done until this one is complete.

**Comment by genxhero** [comment]
Are you the one that does the checking or am I the one with the checking?
I'm kind of confused on that

**Comment by genxhero** [comment]
Checked of a few lets see if it takes

**Comment by genxhero** [comment]
the styling on the signup is i think the last thing that i am certain needs work...the only issue right now is the errors.

**Comment by genxhero** [comment]
Hows it all look?

**Comment by s-pangburn** [comment]
Hey Aaron!

Sorry for the delay, been swamped with various bugs I needed to help with today. This all looks good! My only feedback, and this is kind of a nitpick, is your errors modal should match the size of your sessionForm component. 

That's all though! I'll mark this MVP as complete. Good job!
